# Generated by Django 4.2.9 on 2024-01-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('typed', models.CharField(help_text='Typed Like this -> Developer,Devops', max_length=255, verbose_name='Typed')),
                ('facebook', models.URLField(verbose_name='facebook')),
                ('twitter', models.URLField(verbose_name='Twitter')),
                ('linkedin', models.URLField(verbose_name='LinkedIn')),
                ('instagram', models.URLField(verbose_name='Instagram')),
                ('skype', models.URLField(verbose_name='Skype')),
            ],
        ),
    ]
