# Generated by Django 4.2.9 on 2024-01-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_count', models.IntegerField(default=1, verbose_name='Happy Clients')),
                ('projects', models.IntegerField(default=1, verbose_name='Projects')),
                ('hours_support', models.IntegerField(default=1, verbose_name='Hours Of Support')),
                ('awards', models.IntegerField(default=1, verbose_name='Awards')),
            ],
        ),
    ]
