# Generated by Django 4.2.9 on 2024-01-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_facts'),
    ]

    operations = [
        migrations.AddField(
            model_name='facts',
            name='description',
            field=models.CharField(default='Facts', max_length=255, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
