# Generated by Django 4.2.9 on 2024-01-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Common Description About Skill Set')),
            ],
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
    ]
