# Generated by Django 4.2.9 on 2024-01-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(verbose_name='About Heading')),
                ('title', models.CharField(max_length=255, verbose_name='About Title')),
                ('about_img', models.ImageField(upload_to='about/', verbose_name='About Image')),
                ('dob', models.DateField(verbose_name='Date of Birthday')),
                ('website', models.CharField(max_length=255, verbose_name='Website URL')),
                ('phone', models.BigIntegerField(default=0)),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('age', models.IntegerField(default=0, verbose_name='Age')),
                ('degree', models.CharField(max_length=255, verbose_name='Degree')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('freelance', models.BooleanField(default=False, verbose_name='Freelancing')),
            ],
        ),
    ]
