# Generated by Django 4.2.9 on 2024-01-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='summury',
            field=models.CharField(default='Senior Devops Engineer @ Allianz', max_length=255, verbose_name='Short Summury'),
        ),
    ]
