# Generated by Django 4.2.9 on 2024-01-31 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_heading', models.CharField(default='RESUME', max_length=50, verbose_name='Resume heading')),
                ('short_des', models.CharField(max_length=255, verbose_name='Resume Short Description')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('summary', models.CharField(max_length=255, verbose_name='Summary')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('phone', models.IntegerField(max_length=10, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Profession Title')),
                ('company', models.CharField(max_length=255, verbose_name='Company Name')),
                ('location', models.CharField(max_length=255, verbose_name='Company Location')),
                ('year_start', models.DateField(verbose_name='Start Year')),
                ('year_end', models.DateField(blank=True, null=True, verbose_name='End Year')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeApp.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100, verbose_name='Degree')),
                ('institution', models.CharField(max_length=255, verbose_name='Institution')),
                ('year_start', models.DateField(verbose_name='Start Year')),
                ('year_end', models.DateField(blank=True, null=True, verbose_name='End Year')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeApp.resume')),
            ],
        ),
    ]
