# Generated by Django 4.2.9 on 2024-01-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0002_award_experience_awards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('designation', models.CharField(max_length=100, verbose_name='Designation')),
                ('quotes', models.CharField(max_length=255, verbose_name='Quotes')),
                ('testimonials_img', models.ImageField(upload_to='testimonials/', verbose_name='Testimonials Image')),
            ],
        ),
    ]
